#!/bin/bash
orig_dir="$PWD"
trap 'cd "$orig_dir"' EXIT

source ~/.myzshfuncs

# Go to the project directory
cd ~/Projects/PeriodicTable || exit

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

# Activate the virtual environment
source venv/bin/activate

# Upgrade pip and core packaging tools
pip install --upgrade pip setuptools wheel

# Install required Python dependencies
pip install pygobject numpy matplotlib scipy

# Run the app from the project bin directory
cd bin || exit
clone_terminal 
./ptbl

# Deactivate the virtual environment
deactivate
